version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: CabinetOpt
    command: gunicorn CabinetOpt.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=cabinet_opt

volumes:
  postgres_data:
